# Generated by Django 5.1.3 on 2024-12-06 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Booking Date')),
                ('timeslot', models.CharField(choices=[('1', 'Timeslot 1'), ('2', 'Timeslot 2'), ('3', 'Timeslot 3'), ('4', 'Timeslot 4'), ('5', 'Timeslot 5'), ('OTHER', 'Other (Please Add In Notes)')], max_length=15, verbose_name='Timeslot')),
                ('room', models.CharField(max_length=10, verbose_name='Room')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=15, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('Equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookings.equipment')),
            ],
        ),
    ]
