"""
Django settings for TrolleyProblem project.

Generated by 'django-admin startproject' using Django 5.1.3.

This file contains settings for development purposes.
Ensure sensitive data is securely stored and use a different settings file.
"""

from pathlib import Path

# base directory for the project
BASE_DIR = Path(__file__).resolve().parent.parent

# authentication urls and redirects
LOGIN_URL = '/login/'   # redirects here for not logged in users
LOGIN_REDIRECT_URL = '/'    # redirects here after successful login
LOGOUT_REDIRECT_URL = '/'   # redirects here after logout

# development settings - unsuitable for production
# if looking to deploy, see the django deployment checklist
# https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'example-secret-key-CHANGE-ME'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# hosts allowed to serve this app, update for production
ALLOWED_HOSTS = []


# installed apps
INSTALLED_APPS = [
    # django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # booking app
    'Bookings',
    # auth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',
]

# middleware config
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# root url config
ROOT_URLCONF = 'TrolleyProblem.urls'

# template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent.parent / 'frontend' / 'templates'],    #ensure this directory exists and is valid
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Bookings.context_processors.enable_microsoft_oauth',
            ],
        },
    },
]

# wsgi app
WSGI_APPLICATION = 'TrolleyProblem.wsgi.application'

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIAL_AUTH_MICROSOFT_REDIRECT_URI = 'http://localhost:8000/accounts/microsoft/login/callback/'
SITE_URL = 'http://localhost:8000'
SOCIALACCOUNT_LOGIN_ON_GET=True
ENABLE_MICROSOFT_OAUTH = True  # set to True if you want to use Microsoft OAuth

SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'SCOPE': ['openid', 'email', 'profile',],
        'AUTH_PARAMS': {
            'response_type': 'code',
            # 'tenant': 'TENANT ID FOR ORGANISATION SSO'
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
    }
}

SITE_ID = 1

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',    # path to sqlite file
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# localisation settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# static file settings
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR.parent.parent / 'frontend' / 'static', # ensure this folder exists and is valid
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# email sending settings CHANGEME

EMAIL_NOTIFICATIONS_ENABLED = False # set to TRUE to enable email notifications

"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # Replace with your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your.email@your-domain.com'  # Your email address
EMAIL_HOST_PASSWORD = 'Password1'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'sender.email@your-domain.com' # Email to be sent from
"""
